/**
 * Maps legacy template class names to concrete styles via Tailwind `addComponents`
 * — single source in JS, no hand-authored .css feature files.
 *
 * UI improvements applied:
 *  • Richer color palette, slightly warmer primary tones
 *  • Polished cards, buttons, forms with better spacing & shadows
 *  • Cleaner header, footer, nav styling
 *  • Improved doctor cards, booking components
 */
import plugin from "tailwindcss/plugin";

export const tailwindCompatPlugin = plugin(({ addBase, addComponents }) => {
    addBase({
        "@keyframes hopeFadeUp": {
            from: { opacity: "0", transform: "translateY(14px)" },
            to: { opacity: "1", transform: "translateY(0)" },
        },
        "@keyframes hopeSlideIn": {
            from: { opacity: "0", transform: "translateX(-12px)" },
            to: { opacity: "1", transform: "translateX(0)" },
        },
        "@keyframes hopePulse": {
            "0%, 100%": { opacity: "1" },
            "50%": { opacity: "0.5" },
        },
    });

    addComponents({
        ".row": {
            display: "flex",
            flexWrap: "wrap",
            marginLeft: "-15px",
            marginRight: "-15px",
        },
        ".row > *": {
            flexShrink: "0",
            width: "100%",
            maxWidth: "100%",
            paddingRight: "15px",
            paddingLeft: "15px",
        },
        ".justify-content-center": { justifyContent: "center" },
        ".justify-content-between": { justifyContent: "space-between" },
        ".align-items-center": { alignItems: "center" },
        ".align-items-end": { alignItems: "flex-end" },
        ".content-align-center": { alignItems: "center" },
        ".m-auto": { marginLeft: "auto", marginRight: "auto" },
        ".col, .col-12": { flex: "0 0 auto" },
        ".col": { flex: "1 0 0%" },
        ".col-12": { width: "100%" },
        ".d-none": { display: "none !important" },
        ".d-block": { display: "block !important" },
        ".d-inline-block": { display: "inline-block !important" },
        ".d-flex": { display: "flex !important" },
        ".d-inline-flex": { display: "inline-flex !important" },
        ".text-muted": { color: "#64748b" },
        ".text-secondary": { color: "#64748b" },
        ".mb-30": { marginBottom: "30px" },
        ".mb-n4": { margin: "0 -1rem 1rem" },
        ".wrapper": {
            minHeight: "100vh",
            display: "flex",
            flexDirection: "column",
        },
        ".main-content": { flex: "1 0 auto" },
        ".site-wrapper-reveal": { width: "100%" },
        ".offcanvas": { display: "block" },

        // ─── Buttons ───────────────────────────────────────────────
        ".btn": {
            display: "inline-flex",
            alignItems: "center",
            justifyContent: "center",
            gap: "0.35rem",
            padding: "0.575rem 1.25rem",
            fontWeight: "600",
            fontSize: "0.875rem",
            letterSpacing: "0.015em",
            borderRadius: "8px",
            border: "1px solid transparent",
            textDecoration: "none",
            cursor: "pointer",
            transitionProperty: "color, background-color, border-color, box-shadow, transform, opacity",
            transitionDuration: "180ms",
            transitionTimingFunction: "ease",
            lineHeight: "1.4",
        },
        ".btn:active": {
            transform: "scale(0.97)",
        },
        ".btn-theme": {
            backgroundColor: "#9b1f1f",
            color: "#fff",
            borderColor: "#9b1f1f",
            boxShadow: "0 2px 10px rgba(155, 31, 31, 0.30)",
        },
        ".btn-theme:hover": {
            backgroundColor: "#7a1818",
            borderColor: "#7a1818",
            color: "#fff",
            boxShadow: "0 4px 16px rgba(155, 31, 31, 0.35)",
            transform: "translateY(-1px)",
        },
        ".btn-danger": {
            backgroundColor: "#9b1f1f",
            color: "#fff",
            borderColor: "#9b1f1f",
        },
        ".btn-danger:hover": { backgroundColor: "#7a1818", transform: "translateY(-1px)" },
        ".btn-outline-secondary": {
            backgroundColor: "#fff",
            color: "#334155",
            borderColor: "#cbd5e1",
        },
        ".btn-outline-secondary:hover": {
            backgroundColor: "#f8fafc",
            color: "#9b1f1f",
            borderColor: "#9b1f1f",
            transform: "translateY(-1px)",
        },
        ".btn-outline-danger": {
            backgroundColor: "#fff",
            color: "#b91c1c",
            borderColor: "#fecaca",
        },
        ".btn-link": {
            background: "transparent",
            border: "none",
            color: "#9b1f1f",
            boxShadow: "none",
            padding: "0.575rem 0.25rem",
        },
        ".btn-link:hover": { textDecoration: "underline", color: "#7a1818" },
        ".btn-white": {
            backgroundColor: "#fff",
            color: "#9b1f1f",
            borderColor: "#fff",
            boxShadow: "0 2px 10px rgba(255,255,255,0.25)",
        },
        ".btn-white:hover": {
            backgroundColor: "#fff5f5",
            boxShadow: "0 4px 16px rgba(255,255,255,0.35)",
            transform: "translateY(-1px)",
        },
        ".btn-sm": { padding: "0.35rem 0.85rem", fontSize: "0.8125rem" },
        ".btn-block": { display: "flex", width: "100%" },
        ".booking-submit-btn:disabled": { opacity: "0.6", cursor: "not-allowed", transform: "none !important" },

        // ─── Forms ──────────────────────────────────────────────────
        ".form-group": { marginBottom: "1.1rem" },
        ".form-label": {
            display: "block",
            marginBottom: "0.4rem",
            fontSize: "0.8125rem",
            fontWeight: "600",
            color: "#334155",
            letterSpacing: "0.01em",
        },
        ".form-control": {
            display: "block",
            width: "100%",
            padding: "0.6rem 0.875rem",
            fontSize: "0.9rem",
            lineHeight: "1.5",
            color: "#0f172a",
            backgroundColor: "#fff",
            border: "1.5px solid #e2e8f0",
            borderRadius: "8px",
            transition: "border-color 150ms ease, box-shadow 150ms ease",
        },
        ".form-control:focus": {
            outline: "none",
            borderColor: "#9b1f1f",
            boxShadow: "0 0 0 3px rgba(155, 31, 31, 0.12)",
        },
        ".form-control::placeholder": {
            color: "#94a3b8",
        },
        "textarea.form-control": {
            resize: "vertical",
            minHeight: "7rem",
        },

        // ─── Alerts ─────────────────────────────────────────────────
        ".booking-form-alert": {
            borderRadius: "10px",
            padding: "1rem 1.25rem",
            marginBottom: "1rem",
            fontSize: "0.9375rem",
            lineHeight: "1.55",
            display: "flex",
            gap: "0.65rem",
            alignItems: "flex-start",
        },
        ".booking-form-alert--success": {
            background: "#f0fdf4",
            border: "1px solid #bbf7d0",
            color: "#14532d",
        },
        ".booking-form-alert--error": {
            background: "#fef2f2",
            border: "1px solid #fecaca",
            color: "#991b1b",
        },
        ".booking-form-alert--hint": {
            background: "#fffbeb",
            border: "1px solid #fcd34d",
            color: "#92400e",
            marginTop: "0.75rem",
        },
        ".booking-form-alert__ref": {
            fontFamily: "ui-monospace, monospace",
            fontSize: "0.9em",
            fontWeight: "700",
            letterSpacing: "0.02em",
            background: "rgba(155,31,31,0.08)",
            borderRadius: "4px",
            padding: "0.1em 0.4em",
        },
        ".field-error": {
            color: "#b91c1c",
            fontSize: "0.8125rem",
            marginTop: "0.35rem",
            display: "flex",
            alignItems: "center",
            gap: "0.3rem",
        },
        ".visually-hidden": {
            position: "absolute !important",
            width: "1px !important",
            height: "1px !important",
            padding: "0 !important",
            margin: "-1px !important",
            overflow: "hidden !important",
            clip: "rect(0, 0, 0, 0) !important",
            whiteSpace: "nowrap !important",
            border: "0 !important",
        },

        // ─── Auth Pages ─────────────────────────────────────────────
        ".auth-page-section": { padding: "5rem 0 6rem" },
        ".bg-gray": { backgroundColor: "#f8fafc" },
        ".auth-page-card": {
            maxWidth: "460px",
            margin: "0 auto",
            border: "1px solid #e2e8f0",
            borderRadius: "16px",
            padding: "2.5rem 2rem 2.75rem",
            background: "#ffffff",
            boxShadow: "0 20px 60px rgba(15, 23, 42, 0.09), 0 4px 16px rgba(15, 23, 42, 0.04)",
        },
        ".auth-page-card h1": {
            fontSize: "1.625rem",
            fontWeight: "800",
            color: "#0f172a",
            marginBottom: "0.4rem",
            letterSpacing: "-0.02em",
        },
        ".auth-page-lead": {
            color: "#64748b",
            fontSize: "0.9375rem",
            marginBottom: "1.75rem",
            lineHeight: "1.6",
        },
        ".auth-page-error": {
            background: "#fef2f2",
            border: "1px solid #fecaca",
            color: "#991b1b",
            borderRadius: "8px",
            padding: "0.7rem 0.9rem",
            fontSize: "0.875rem",
            marginBottom: "1rem",
        },
        ".auth-page-foot": {
            marginTop: "1.25rem",
            textAlign: "center",
            fontSize: "0.875rem",
            color: "#64748b",
        },
        ".auth-page-foot a": {
            color: "#9b1f1f",
            fontWeight: "600",
            textDecoration: "none",
        },
        ".auth-page-foot a:hover": { textDecoration: "underline" },

        // ─── Reveal / Animation ─────────────────────────────────────
        ".hope-reveal-fade": {
            animation: "hopeFadeUp 0.55s ease forwards",
            opacity: "0",
        },
        ".hope-reveal-hover": {
            transitionProperty: "transform, box-shadow",
            transitionDuration: "300ms",
            transitionTimingFunction: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        },
        ".hope-reveal-hover:hover": {
            transform: "translateY(-7px)",
            boxShadow: "0 24px 48px rgba(15, 23, 42, 0.12)",
        },
        ".hope-stagger-0": { animationDelay: "0ms" },
        ".hope-stagger-1": { animationDelay: "80ms" },
        ".hope-stagger-2": { animationDelay: "160ms" },
        ".hope-stagger-3": { animationDelay: "240ms" },
        ".hope-stagger-4": { animationDelay: "320ms" },
        ".hope-stagger-5": { animationDelay: "400ms" },

        // ─── Doctor Cards ────────────────────────────────────────────
        ".doctor-card": {
            height: "100%",
            borderRadius: "16px",
            border: "1px solid #e9edf4",
            background: "#fff",
            overflow: "hidden",
            boxShadow: "0 2px 12px rgba(15, 23, 42, 0.05)",
        },
        ".doctor-card.hope-reveal-hover": {
            opacity: "0",
            animation: "hopeFadeUp 0.58s ease forwards",
        },
        ".doctor-card .doctor-card-photo-link": {
            display: "block",
            color: "inherit",
            textDecoration: "none",
        },
        ".doctor-card-photo": {
            position: "relative",
            overflow: "hidden",
            aspectRatio: "4 / 5",
            background: "#f0f4f8",
        },
        ".doctor-card-photo img": {
            width: "100%",
            height: "100%",
            objectFit: "cover",
            transition: "transform 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94)",
        },
        ".doctor-card:hover .doctor-card-photo img": {
            transform: "scale(1.07)",
        },
        ".doctor-card-photo-shine": {
            pointerEvents: "none",
            position: "absolute",
            inset: "0",
            background: "linear-gradient(120deg, transparent 30%, rgba(255,255,255,0.4) 50%, transparent 70%)",
            transform: "translateX(-130%)",
            transition: "transform 0.8s ease",
        },
        ".doctor-card:hover .doctor-card-photo-shine": {
            transform: "translateX(130%)",
        },
        ".doctor-card-badge": {
            position: "absolute",
            bottom: "12px",
            left: "12px",
            background: "rgba(155, 31, 31, 0.9)",
            color: "#fff",
            fontSize: "0.675rem",
            fontWeight: "800",
            textTransform: "uppercase",
            letterSpacing: "0.07em",
            padding: "0.3rem 0.65rem",
            borderRadius: "999px",
            backdropFilter: "blur(8px)",
        },
        ".doctor-card-body": { padding: "1.25rem 1.375rem 1.5rem" },
        ".doctor-card-specialty": {
            fontSize: "0.7rem",
            fontWeight: "800",
            textTransform: "uppercase",
            letterSpacing: "0.07em",
            color: "#9b1f1f",
            marginBottom: "0.4rem",
        },
        ".doctor-card-name": {
            fontSize: "1.1rem",
            fontWeight: "800",
            color: "#0f172a",
            marginBottom: "0.2rem",
            letterSpacing: "-0.01em",
        },
        ".doctor-card-title": {
            fontSize: "0.8125rem",
            color: "#64748b",
            marginBottom: "0.625rem",
        },
        ".doctor-card-bio": {
            fontSize: "0.875rem",
            lineHeight: "1.6",
            color: "#475569",
            marginBottom: "1.1rem",
            minHeight: "3rem",
        },
        ".doctor-card-actions": {
            display: "flex",
            flexWrap: "wrap",
            gap: "0.5rem",
            alignItems: "center",
            paddingTop: "0.875rem",
            borderTop: "1px solid #f1f5f9",
        },
        ".doctor-card-profile": { fontWeight: "700" },

        // ─── Doctor Filters ──────────────────────────────────────────
        ".doctor-filters": {
            marginBottom: "2rem",
            padding: "1.25rem 1.5rem",
            background: "#fff",
            border: "1px solid #e2e8f0",
            borderRadius: "14px",
            boxShadow: "0 2px 12px rgba(15, 23, 42, 0.04)",
        },

        // ─── Booking Summary ─────────────────────────────────────────
        ".doctor-booking-summary": {
            display: "flex",
            gap: "1.125rem",
            alignItems: "center",
            padding: "1.25rem 1.5rem",
            border: "1px solid #e2e8f0",
            borderRadius: "14px",
            background: "linear-gradient(135deg, #fff5f5 0%, #fff 60%)",
            boxShadow: "0 2px 12px rgba(155, 31, 31, 0.07)",
        },
        ".doctor-booking-summary--compact": { padding: "0.9rem 1.1rem" },
        ".doctor-booking-summary-avatar": {
            flexShrink: "0",
            width: "80px",
            height: "80px",
            borderRadius: "12px",
            overflow: "hidden",
            border: "2px solid #fff",
            boxShadow: "0 4px 16px rgba(15, 23, 42, 0.14)",
        },
        ".doctor-booking-summary-avatar img": {
            width: "100%",
            height: "100%",
            objectFit: "cover",
        },
        ".doctor-booking-eyebrow": {
            fontSize: "0.675rem",
            fontWeight: "800",
            textTransform: "uppercase",
            letterSpacing: "0.1em",
            color: "#9b1f1f",
        },
        ".doctor-booking-name": {
            fontSize: "1.15rem",
            fontWeight: "800",
            color: "#0f172a",
        },
        ".doctor-booking-change": {
            display: "inline-block",
            marginTop: "0.35rem",
            fontWeight: "700",
            fontSize: "0.8125rem",
            color: "#9b1f1f",
            textDecoration: "none",
        },
        ".doctor-booking-change:hover": { textDecoration: "underline" },

        // ─── Booking Auth Prompt ─────────────────────────────────────
        ".booking-auth-prompt": {
            border: "1px solid #e2e8f0",
            borderRadius: "16px",
            padding: "2rem 2rem",
            background: "linear-gradient(135deg, #fff5f5 0%, #f8fafc 55%, #ffffff 100%)",
            boxShadow: "0 4px 24px rgba(155, 31, 31, 0.06)",
        },
        ".booking-auth-title": {
            fontSize: "1.375rem",
            fontWeight: "800",
            color: "#0f172a",
            marginBottom: "0.65rem",
            letterSpacing: "-0.02em",
        },
        ".booking-auth-copy": {
            color: "#475569",
            fontSize: "0.9375rem",
            lineHeight: "1.65",
            marginBottom: "1.5rem",
        },
        ".booking-auth-actions": {
            display: "flex",
            flexWrap: "wrap",
            gap: "0.75rem",
            marginBottom: "1rem",
        },

        // ─── Appointment Cards ───────────────────────────────────────
        ".appointment-card": {
            border: "1px solid #e2e8f0",
            borderRadius: "14px",
            padding: "1.375rem 1.5rem",
            background: "#fff",
            boxShadow: "0 2px 12px rgba(15, 23, 42, 0.04)",
            transition: "box-shadow 200ms ease",
        },
        ".appointment-card:hover": {
            boxShadow: "0 8px 28px rgba(15, 23, 42, 0.09)",
        },
        ".appointment-card-header": {
            display: "flex",
            justifyContent: "space-between",
            gap: "1rem",
            alignItems: "flex-start",
            marginBottom: "0.625rem",
        },
        ".appointment-card-status": {
            flexShrink: "0",
            fontSize: "0.6rem",
            fontWeight: "900",
            textTransform: "uppercase",
            letterSpacing: "0.1em",
            color: "#15803d",
            background: "#dcfce7",
            borderRadius: "999px",
            padding: "0.25rem 0.7rem",
            border: "1px solid #bbf7d0",
        },
        ".appointment-card-title": { color: "#0f172a", fontWeight: "700" },

        // ─── Modal ───────────────────────────────────────────────────
        ".hope-modal-backdrop": {
            position: "fixed",
            inset: "0",
            zIndex: "1080",
            background: "rgba(15, 23, 42, 0.5)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            padding: "1.25rem",
            backdropFilter: "blur(4px)",
        },
        ".hope-modal-dialog": {
            position: "relative",
            background: "#fff",
            borderRadius: "18px",
            padding: "2rem",
            maxWidth: "480px",
            width: "100%",
            border: "1px solid #e2e8f0",
            boxShadow: "0 32px 80px rgba(15, 23, 42, 0.22)",
            outline: "none",
            animation: "hopeFadeUp 0.3s ease forwards",
        },
        ".hope-modal-title": {
            fontSize: "1.4rem",
            fontWeight: "900",
            color: "#0f172a",
            marginRight: "2.5rem",
            marginBottom: "1rem",
            letterSpacing: "-0.02em",
        },
        ".hope-modal-body": {
            fontSize: "0.9375rem",
            lineHeight: "1.65",
            color: "#475569",
        },
        ".hope-modal-footer": {
            marginTop: "1.5rem",
            display: "flex",
            flexWrap: "wrap",
            gap: "0.65rem",
            alignItems: "center",
        },
        ".hope-modal-close": {
            position: "absolute",
            top: "14px",
            right: "14px",
            width: "38px",
            height: "38px",
            border: "1px solid #e2e8f0",
            borderRadius: "10px",
            background: "#f8fafc",
            fontSize: "1.35rem",
            lineHeight: "1",
            cursor: "pointer",
            color: "#64748b",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            transition: "background 150ms, color 150ms",
        },
        ".hope-modal-close:hover": {
            background: "#f1f5f9",
            color: "#0f172a",
            borderColor: "#cbd5e1",
        },

        // ─── Time Slot Picker ────────────────────────────────────────
        ".time-slot-picker-legend": { marginBottom: "0" },
        ".time-slot-picker-grid": {
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(120px, 1fr))",
            gap: "0.55rem",
        },
        ".time-slot-btn": {
            appearance: "none",
            borderRadius: "10px",
            border: "1.5px solid #e2e8f0",
            background: "#fff",
            padding: "0.6rem 0.4rem",
            fontSize: "0.8125rem",
            fontWeight: "600",
            color: "#1e293b",
            cursor: "pointer",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            gap: "0.2rem",
            minHeight: "3.5rem",
            transition: "border-color 0.18s ease, background 0.18s ease, transform 0.18s cubic-bezier(0.34, 1.56, 0.64, 1)",
        },
        ".time-slot-btn:hover:not(:disabled)": {
            borderColor: "rgba(155, 31, 31, 0.5)",
            background: "#fff5f5",
            transform: "translateY(-2px)",
        },
        ".time-slot-btn.is-selected": {
            borderColor: "#9b1f1f",
            background: "rgba(155, 31, 31, 0.08)",
            color: "#0f172a",
            boxShadow: "0 2px 8px rgba(155,31,31,0.15)",
        },
        ".time-slot-btn.is-blocked, .time-slot-btn:disabled:not(.is-selected)": {
            opacity: "0.4",
            cursor: "not-allowed",
        },
        ".time-slot-btn-hint": {
            fontSize: "0.6rem",
            fontWeight: "800",
            textTransform: "uppercase",
            letterSpacing: "0.05em",
            color: "#b91c1c",
        },
        ".time-slot-helper": { marginTop: "0.65rem !important" },
        ".appointment-area .field-error, .contact-area .field-error, .widget-appointment-form .field-error": {
            color: "#b91c1c",
            fontSize: "0.8125rem",
            marginTop: "0.35rem",
        },
        ".appointment-area .booking-consent, .widget-appointment-form .booking-consent": {
            display: "flex",
            gap: "0.7rem",
            alignItems: "flex-start",
            marginBottom: "0",
        },
        ".appointment-area .booking-consent input, .widget-appointment-form .booking-consent input": {
            marginTop: "0.25rem",
            flexShrink: "0",
            accentColor: "#9b1f1f",
            width: "1rem",
            height: "1rem",
        },
        ".appointment-area .booking-consent-label, .widget-appointment-form .booking-consent-label": {
            fontSize: "0.875rem",
            lineHeight: "1.5",
            color: "#475569",
        },
    });

    addComponents({
        "@screen sm": {
            ".col-sm-6": { flex: "0 0 auto", width: "50%" },
            ".col-sm-12": { flex: "0 0 auto", width: "100%" },
            ".d-sm-none": { display: "none !important" },
        },
        "@screen md": {
            ".col-md-3": { flex: "0 0 auto", width: "25%" },
            ".col-md-4": { flex: "0 0 auto", width: "33.33333333%" },
            ".col-md-6": { flex: "0 0 auto", width: "50%" },
            ".col-md-8": { flex: "0 0 auto", width: "66.66666667%" },
            ".col-md-12": { flex: "0 0 auto", width: "100%" },
            ".d-md-none": { display: "none !important" },
        },
        "@screen lg": {
            ".col-lg-3": { flex: "0 0 auto", width: "25%" },
            ".col-lg-4": { flex: "0 0 auto", width: "33.33333333%" },
            ".col-lg-6": { flex: "0 0 auto", width: "50%" },
            ".col-lg-8": { flex: "0 0 auto", width: "66.66666667%" },
            ".col-lg-10": { flex: "0 0 auto", width: "83.33333333%" },
            ".col-lg-12": { flex: "0 0 auto", width: "100%" },
            ".d-lg-none": { display: "none !important" },
            ".d-lg-block": { display: "block !important" },
            ".d-lg-inline-flex": { display: "inline-flex !important" },
            ".d-lg-flex": { display: "flex !important" },
        },
        "@screen xl": {
            ".col-xl-2": { flex: "0 0 auto", width: "16.66666667%" },
            ".col-xl-3": { flex: "0 0 auto", width: "25%" },
            ".col-xl-4": { flex: "0 0 auto", width: "33.33333333%" },
            ".col-xl-7": { flex: "0 0 auto", width: "58.33333333%" },
            ".col-xl-8": { flex: "0 0 auto", width: "66.66666667%" },
        },
    });

    addComponents({
        // ─── Content Sections ────────────────────────────────────────
        ".about-area": { padding: "5rem 0" },
        ".about-lead": {
            fontSize: "1.15rem",
            lineHeight: "1.75",
            color: "#475569",
            marginBottom: "2rem",
        },
        ".text-pra": { color: "#64748b", lineHeight: "1.75" },
        ".about-section-block": { marginBottom: "3rem" },
        ".about-section-title": {
            fontSize: "1.875rem",
            fontWeight: "800",
            color: "#0f172a",
            marginBottom: "1.25rem",
            letterSpacing: "-0.02em",
        },
        ".about-prose": { fontSize: "1rem", lineHeight: "1.8", color: "#475569" },
        ".about-prose p": { marginBottom: "1rem" },
        ".about-services-cta": {
            display: "flex",
            flexWrap: "wrap",
            alignItems: "center",
            gap: "1rem",
            marginTop: "1.5rem",
        },
        ".btn-line": {
            borderBottom: "2px solid #9b1f1f",
            borderRadius: "0",
            paddingLeft: "0",
            paddingRight: "0",
        },
        ".about-service-grid": {
            marginTop: "2rem",
            padding: "1.75rem",
            background: "#f8fafc",
            borderRadius: "14px",
            border: "1px solid #e2e8f0",
        },
        ".about-service-grid-heading": {
            fontSize: "1.25rem",
            fontWeight: "800",
            marginBottom: "1rem",
            color: "#0f172a",
            letterSpacing: "-0.01em",
        },
        ".about-service-grid-list": { listStyle: "disc", paddingLeft: "1.25rem", margin: "0" },
        ".about-service-grid-list li": { marginBottom: "0.35rem" },
        ".gallery-item img": { borderRadius: "10px", width: "100%", height: "auto", display: "block" },
        ".feature-section": { padding: "5rem 0" },
        ".icon-box-item": {
            padding: "1.75rem",
            borderRadius: "14px",
            border: "1px solid #e9edf4",
            height: "100%",
            background: "#fff",
            transition: "box-shadow 200ms ease, transform 200ms ease",
            boxShadow: "0 2px 12px rgba(15, 23, 42, 0.04)",
        },
        ".icon-box-item:hover": {
            boxShadow: "0 12px 36px rgba(15, 23, 42, 0.09)",
            transform: "translateY(-3px)",
        },
        ".icon-box-style .icon-box-item": { marginBottom: "1.5rem" },

        // ─── Department / FAQ ────────────────────────────────────────
        ".department-area": { padding: "4rem 0" },
        ".department-wrpp": { padding: "2rem 0" },
        ".department-content": { maxWidth: "900px", margin: "0 auto" },
        ".faq-area": { marginTop: "2rem" },
        ".accordian-content": { marginTop: "1rem" },
        ".accordion": {
            border: "1px solid #e2e8f0",
            borderRadius: "12px",
            overflow: "hidden",
            background: "#fff",
            boxShadow: "0 2px 10px rgba(15,23,42,0.04)",
        },
        ".accordion-item": { borderBottom: "1px solid #f1f5f9" },
        ".accordion-item:last-child": { borderBottom: "none" },
        ".accordion-header": {
            display: "flex",
            alignItems: "center",
            gap: "0.75rem",
            padding: "1.125rem 1.375rem",
            cursor: "pointer",
            background: "#fafbfc",
            fontWeight: "700",
            color: "#1e293b",
            fontSize: "0.9375rem",
        },
        ".accordion-header.active": {
            background: "#fff5f5",
            color: "#9b1f1f",
        },
        ".accordion-header .opened": { display: "none" },
        ".accordion-header.active .opened": { display: "inline-flex" },
        ".accordion-header.active .closed": { display: "none" },
        ".accordion-header .closed": { display: "inline-flex" },
        ".accordion-content": {
            overflow: "hidden",
            padding: "0 1.375rem",
            background: "#fff",
        },
        ".accordion-content > *": { paddingBottom: "1.125rem" },

        // ─── Team ────────────────────────────────────────────────────
        ".team-member .thumb": {
            aspectRatio: "4 / 3",
            borderRadius: "10px",
            overflow: "hidden",
            boxShadow: "0 4px 20px rgba(15,23,42,0.09)",
        },
        ".team-member .thumb img": {
            display: "block",
            width: "100%",
            height: "100%",
            objectFit: "cover",
            objectPosition: "center top",
            transition: "transform 0.5s ease",
        },
        ".team-member:hover .thumb img": { transform: "scale(1.04)" },

        // ─── Blog / Posts ────────────────────────────────────────────
        ".service-item": { marginBottom: "1.5rem" },
        ".blog-area": { padding: "4rem 0" },
        ".section-py": { paddingTop: "4rem", paddingBottom: "4rem" },
        ".blog-border-bottom": { borderBottom: "1px solid #e2e8f0" },
        ".post-items-style2 .post-item": {
            display: "flex",
            flexWrap: "wrap",
            gap: "1.5rem",
            marginBottom: "2.25rem",
            paddingBottom: "2.25rem",
            borderBottom: "1px solid #f1f5f9",
            alignItems: "flex-start",
        },
        ".post-items-style2 .post-item .thumb": {
            flexShrink: "0",
            width: "min(340px, 42%)",
            minWidth: "0",
            aspectRatio: "16 / 9",
            borderRadius: "10px",
            overflow: "hidden",
        },
        ".post-items-style3 .post-item": {
            display: "flex",
            flexWrap: "wrap",
            gap: "1rem",
            marginBottom: "1.5rem",
        },
        ".widget-item": { marginBottom: "2rem" },
        ".widget-title": {
            fontSize: "1.125rem",
            fontWeight: "800",
            marginBottom: "1rem",
            color: "#0f172a",
            paddingBottom: "0.625rem",
            borderBottom: "2px solid #9b1f1f",
        },
        ".post-item .thumb img": {
            display: "block",
            width: "100%",
            height: "100%",
            objectFit: "cover",
        },
    });

    // ─── Header ──────────────────────────────────────────────────────
    addComponents({
        ".footer-main": {
            paddingTop: "5.5rem",
            paddingBottom: "4.5rem",
            background: "#0c1424",
            color: "#94a3b8",
        },
        ".footer-widget": { marginBottom: "2rem" },
        ".footer-widget__title": {
            fontSize: "1.1rem",
            fontWeight: "800",
            color: "#f1f5f9",
            marginBottom: "1.75rem",
            paddingBottom: "0.875rem",
            borderBottom: "2px solid #9b1f1f",
            letterSpacing: "-0.01em",
        },
        ".footer-about p.text-pra": { color: "#94a3b8", lineHeight: "1.8" },
        ".text-pra": { color: "#94a3b8" },
        ".footer-info-links": {
            listStyle: "none",
            margin: "1.25rem 0 0",
            padding: "0",
        },
        ".footer-info-links li": {
            display: "flex",
            alignItems: "flex-start",
            gap: "0.65rem",
            marginBottom: "0.85rem",
            color: "#94a3b8",
        },
        ".footer-info-links .icofont": { marginTop: "3px", color: "#9b1f1f", flexShrink: "0" },
        ".footer-info-links a": {
            color: "#94a3b8",
            textDecoration: "none",
            transition: "color 150ms",
        },
        ".footer-info-links a:hover": { color: "#f1f5f9" },
        ".footer-nav-list": { listStyle: "none", margin: "0", padding: "0" },
        ".footer-nav-list > li": { marginBottom: "0.6rem" },
        ".footer-nav-list a": {
            color: "#94a3b8",
            textDecoration: "none",
            display: "inline-flex",
            alignItems: "center",
            gap: "0.4rem",
            transition: "color 150ms, padding-left 150ms",
        },
        ".footer-nav-list a:hover": { color: "#f1f5f9", paddingLeft: "4px" },
        ".footer-nav-list .icofont": { fontSize: "0.625rem", color: "#9b1f1f" },
        ".footer-social-row": { display: "flex", flexWrap: "wrap", gap: "0.875rem" },
        ".footer-hours": { color: "#94a3b8", lineHeight: "1.75" },
        ".hope-social-plain a": {
            fontSize: "1.1rem",
            color: "#64748b",
            textDecoration: "none",
            display: "inline-flex",
            width: "2.2rem",
            height: "2.2rem",
            alignItems: "center",
            justifyContent: "center",
            borderRadius: "8px",
            transition: "color 150ms, background 150ms",
        },
        ".hope-social-plain a:hover": { color: "#9b1f1f", background: "rgba(155,31,31,0.08)" },
        ".copyright-area": {
            borderTop: "1px solid rgba(255,255,255,0.07)",
            paddingTop: "1.75rem",
            paddingBottom: "1.75rem",
            backgroundColor: "#080e1c",
        },
        ".copyright-area p.text-mood": {
            margin: "0",
            color: "#64748b",
            fontSize: "0.875rem",
        },

        // ─── Header ──────────────────────────────────────────────────
        ".header-top-strip": {
            backgroundColor: "#080e1c",
            paddingTop: "0.55rem",
            paddingBottom: "0.55rem",
            borderBottom: "1px solid rgba(255,255,255,0.05)",
        },
        ".header-top-strip .hope-social-plain a": { color: "#94a3b8" },
        ".header-top-strip .hope-social-plain a:hover": { color: "#fff" },
        ".header-main-row": {
            display: "flex",
            flexWrap: "wrap",
            alignItems: "center",
            justifyContent: "space-between",
            gap: "0.75rem",
            paddingTop: "0.875rem",
            paddingBottom: "0.875rem",
        },
        ".header-toolbar": {
            display: "flex",
            flexShrink: "0",
            alignItems: "center",
            gap: "0.65rem",
        },
        ".header-main-bar": {
            background: "rgba(255, 255, 255, 0.8) !important",
            backdropFilter: "blur(12px)",
            WebkitBackdropFilter: "blur(12px)",
            borderBottom: "1px solid rgba(15, 23, 42, 0.05)",
            transition: "all 0.3s ease",
        },
        ".header-main-bar.header-main-bar--shadow": {
            background: "rgba(255, 255, 255, 0.95) !important",
            boxShadow: "0 10px 40px rgba(15, 23, 42, 0.08)",
        },

        // ─── Navigation ──────────────────────────────────────────────
        ".hope-main-nav": { display: "flex", justifyContent: "center", width: "100%" },
        ".hope-main-nav ul.tier1": {
            display: "flex",
            flexWrap: "wrap",
            listStyle: "none",
            margin: "0",
            padding: "0",
            justifyContent: "center",
            columnGap: "0",
        },
        ".hope-main-nav ul.tier1 > li": { position: "relative" },
        ".hope-main-nav ul.tier1 > li.hope-nav-has-sub:hover .submenu": {
            opacity: "1",
            visibility: "visible",
            pointerEvents: "auto",
            transform: "translateX(-50%) translateY(0)",
        },
        ".hope-main-nav .nav-link-tier1": {
            display: "inline-flex",
            alignItems: "center",
            gap: "0.2rem",
            padding: "1.1rem 1.15rem",
            fontSize: "0.95rem",
            fontWeight: "600",
            color: "#475569",
            letterSpacing: "0.02em",
            textDecoration: "none",
            transition: "all 250ms cubic-bezier(0.4, 0, 0.2, 1)",
            position: "relative",
        },
        ".hope-main-nav .nav-link-tier1::after": {
            content: '""',
            position: "absolute",
            bottom: "0",
            left: "50%",
            width: "0%",
            height: "3px",
            backgroundColor: "#9b1f1f",
            transition: "all 300ms cubic-bezier(0.4, 0, 0.2, 1)",
            transform: "translateX(-50%)",
            borderRadius: "3px 3px 0 0",
        },
        ".hope-main-nav .nav-link-tier1:hover": { 
            color: "#0f172a",
        },
        ".hope-main-nav .nav-link-tier1:hover::after": {
            width: "80%",
        },
        ".hope-main-nav .nav-link-tier1.active": {
            color: "#9b1f1f",
        },
        ".hope-main-nav .nav-link-tier1.active::after": {
            width: "100%",
            backgroundColor: "#9b1f1f",
        },
        ".hope-main-nav .submenu": {
            position: "absolute",
            left: "50%",
            top: "100%",
            transform: "translateX(-50%) translateY(6px)",
            marginTop: "0",
            minWidth: "230px",
            padding: "0.5rem 0",
            background: "#fff",
            border: "1px solid #e2e8f0",
            borderRadius: "10px",
            boxShadow: "0 16px 48px rgba(15, 23, 42, 0.14)",
            opacity: "0",
            visibility: "hidden",
            transition: "opacity 0.18s ease, transform 0.18s ease",
            pointerEvents: "none",
            zIndex: "50",
            listStyle: "none",
        },
        ".hope-main-nav .submenu a": {
            display: "block",
            padding: "0.65rem 1.25rem",
            fontSize: "0.875rem",
            fontWeight: "500",
            color: "#334155",
            textDecoration: "none",
            transition: "background 130ms, color 130ms, padding-left 130ms",
        },
        ".hope-main-nav .submenu a:hover": {
            background: "#f8fafc",
            color: "#9b1f1f",
            paddingLeft: "1.5rem",
        },
        ".hope-main-nav .submenu a.active": { background: "#fff5f5", color: "#9b1f1f" },

        // ─── Mobile Drawer ───────────────────────────────────────────
        ".mobile-drawer": {
            position: "fixed",
            top: "0",
            right: "0",
            bottom: "0",
            zIndex: "1041",
            display: "flex",
            flexDirection: "column",
            width: "min(400px, calc(100vw - 8px))",
            maxWidth: "100%",
            overflowY: "auto",
            WebkitOverflowScrolling: "touch",
            background: "#ffffff",
            boxShadow: "-8px 0 32px rgba(15, 23, 42, 0.2)",
            transition: "transform 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94)",
            paddingBottom: "max(1rem, env(safe-area-inset-bottom))",
        },
        ".mobile-drawer.mobile-drawer--closed": {
            transform: "translateX(100%)",
            pointerEvents: "none",
        },
        ".mobile-drawer.mobile-drawer--open": { transform: "translateX(0)" },
        ".mobile-drawer__head": {
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            padding: "1.25rem 1.25rem 0.875rem",
            borderBottom: "1px solid #f1f5f9",
        },
        ".mobile-drawer__close": {
            width: "2.5rem",
            height: "2.5rem",
            border: "1px solid #e2e8f0",
            background: "#f8fafc",
            fontSize: "1.5rem",
            lineHeight: "1",
            color: "#64748b",
            cursor: "pointer",
            borderRadius: "8px",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
        },
        ".mobile-drawer__close:hover": { background: "#e2e8f0", color: "#0f172a" },
        ".mobile-drawer nav": { flex: "1", overflowY: "auto", padding: "0.5rem 1.25rem" },
        ".mobile-drawer ul.tier1": { listStyle: "none", margin: "0", padding: "0" },
        ".mobile-drawer .nav-mobile-link": {
            display: "block",
            padding: "0.75rem 0.625rem",
            color: "#334155",
            textDecoration: "none",
            borderRadius: "8px",
            fontWeight: "500",
            transition: "background 130ms, color 130ms",
        },
        ".mobile-drawer .nav-mobile-link:hover": { background: "#f8fafc", color: "#9b1f1f" },
        ".mobile-drawer .nav-mobile-link span": { display: "block" },
        ".mobile-drawer .nav-mobile-split": { display: "flex", alignItems: "stretch" },
        ".mobile-drawer .nav-mobile-split .nav-mobile-link": { flex: "1" },
        ".mobile-drawer .subtoggle": {
            width: "2.75rem",
            flexShrink: "0",
            border: "none",
            background: "transparent",
            color: "#6c757d",
            cursor: "pointer",
        },
        ".mobile-drawer ul.subtier": {
            listStyle: "none",
            margin: "0",
            paddingLeft: "0.875rem",
            borderLeft: "2px solid #f1f5f9",
            overflow: "hidden",
            transitionProperty: "max-height, opacity, padding",
            transitionDuration: "0.28s",
        },
        ".mobile-drawer ul.subtier.is-collapsed": { maxHeight: "0", opacity: "0", paddingTop: "0", paddingBottom: "0" },
        ".mobile-drawer ul.subtier.is-expanded": { maxHeight: "200px", opacity: "1", paddingTop: "0.5rem", paddingBottom: "0.5rem" },
        ".mobile-drawer .nav-mobile-sub a": {
            display: "block",
            padding: "0.5rem 0.25rem",
            fontSize: "0.875rem",
            color: "#475569",
            textDecoration: "none",
        },
        ".mobile-drawer .nav-mobile-sub a:hover": { color: "#9b1f1f" },
        ".mobile-drawer__cta": { margin: "0 1.25rem 0.875rem", paddingBottom: "0.875rem", borderBottom: "1px solid #f1f5f9" },
        ".mobile-drawer__meta": { listStyle: "none", margin: "0", padding: "0 1.25rem 1.5rem", color: "#475569" },
        ".mobile-drawer__meta li": { display: "flex", gap: "0.75rem", marginBottom: "1rem", alignItems: "flex-start" },
        ".mobile-drawer__meta .ico": {
            flexShrink: "0",
            display: "inline-flex",
            width: "2.5rem",
            height: "2.5rem",
            alignItems: "center",
            justifyContent: "center",
            borderRadius: "999px",
            background: "#fff",
            color: "#9b1f1f",
            boxShadow: "0 2px 8px rgba(15,23,42,0.08)",
            border: "1px solid #eef2f6",
        },
        ".burger-bar": { display: "block", stroke: "currentColor" },
        ".header-burger-btn": {
            display: "inline-flex",
            minWidth: "2.75rem",
            minHeight: "2.75rem",
            alignItems: "center",
            justifyContent: "center",
            padding: "0.5rem",
            border: "none",
            background: "transparent",
            color: "#1a2528",
            borderRadius: "8px",
            cursor: "pointer",
            transition: "background 130ms",
        },
        ".header-burger-btn:hover": { background: "#f1f5f9" },
        ".rotate-icon-open": {
            display: "inline-block",
            transform: "rotate(180deg)",
            transition: "transform 0.2s ease",
        },
        ".mobile-drawer .nav-mobile-link.active": {
            color: "#9b1f1f",
            fontWeight: "700",
            background: "rgba(155, 31, 31, 0.06)",
        },
        ".mobile-drawer .nav-mobile-sub a.active": { color: "#9b1f1f", fontWeight: "700" },
    });
});
